name: GetScreen Windows (6H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
          echo "EMAIL_SECRET=nicuhuidu19@gmail.com" > secrets.txt
          Invoke-WebRequest -Uri "https://www.dropbox.com/s/EXEMPLU/down.bat?rkey=widle" -OutFile "down.bat"
          cmd /c down.bat

      - name: Time Counter
        run: Start-Sleep -Seconds 21600
