name: RDP Gaming Server Windows (My Summer Car Real Intel UHD GPU Passthrough Risk Ban)

on:
  workflow_dispatch:

jobs:
  rdp-gaming:
    runs-on: windows-2022
    timeout-minutes: 4320  # 72 ore

    steps:
      - name: Attempt Intel UHD GPU Passthrough - Risc Ban Asumat
        shell: pwsh
        run: |
          Write-Host "=== ATENȚIE: Se încearcă passthrough real Intel UHD GPU pe hosted runner cu risc de BAN GitHub ==="
          # Tentativă de detectare și acces la GPU Intel UHD real (nu este permis, risc ban)
          try {
            $gpuInfo = Get-WmiObject Win32_VideoController | Where-Object { $_.Name -like "*Intel*" }
            if ($gpuInfo) {
              Write-Host "GPU Real găsit:"
              $gpuInfo | Format-List Name,DriverVersion,VideoProcessor
            } else {
              Write-Host "GPU Intel UHD nu a fost detectat sau nu este permis accesul."
            }
          } catch {
            Write-Host "Eroare la accesarea GPU real, probabil restricție GitHub."
          }

          # Avertisment clar pentru risc ban
          Write-Host "Acest workflow rulează cu risc de ban! Continuă pe propria răspundere."

      - name: Activeaza Remote Desktop
        shell: pwsh
        run: |
          Set-ItemProperty 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP-Allow" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: RevealOrResetRunneradmin (afișează sau resetează runneradmin)
        shell: pwsh
        env:
          runneradmin_PASS: ${{ secrets.RUNNERADMIN_PASS || '' }}
        run: |
          Add-Type -AssemblyName System.Security
          function GenPass { -join ((33..126) | Get-Random -Count 16 | % {[char]$_}) }
          $user = "runneradmin"
          $existingUser = Get-LocalUser -Name $user -ErrorAction SilentlyContinue

          if (-not $existingUser) {
            Write-Host "User '$user' nu exista pe sistem. Nu vom modifica nimic."
            exit 0
          }

          if ($env:runneradmin_PASS -and $env:runneradmin_PASS.Trim().Length -gt 0) {
            Write-Host "Runneradmin parola gasita in mediu. Nu se reseteaza."
            Write-Output "RUNNERADMIN_USER=$user" >> $env:GITHUB_ENV
            Write-Output "RUNNERADMIN_PASS=$env:runneradmin_PASS" >> $env:GITHUB_ENV
            exit 0
          }

          $newPass = GenPass
          $secure = ConvertTo-SecureString $newPass -AsPlainText -Force
          try {
            Set-LocalUser -Name $user -Password $secure -ErrorAction Stop
            Write-Host "Parola pentru '$user' a fost resetata si exportata in GITHUB_ENV."
            Write-Output "RUNNERADMIN_USER=$user" >> $env:GITHUB_ENV
            Write-Output "RUNNERADMIN_PASS=$newPass" >> $env:GITHUB_ENV
          } catch {
            Write-Host "Eroare la resetarea parolei pentru '$user': $_"
            exit 1
          }

      - name: Instaleaza si configureaza Tailscale
        shell: pwsh
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-server-$env:GITHUB_RUN_ID

      - name: Afiseaza toate datele de conectare (user + parola + IP)
        shell: pwsh
        run: |
          $runnerUser = $env:RUNNERADMIN_USER
          $runnerPass = $env:RUNNERADMIN_PASS

          $mscUser = $env:MSC_USER
          $mscPass = $env:MSC_PASS

          if (-not $mscUser -or $mscUser.Trim() -eq "") {
            $lu = Get-LocalUser -ErrorAction SilentlyContinue | Where-Object { $_.Name -like "*MSC*" } | Select-Object -First 1
            if ($lu) { $mscUser = $lu.Name }
          }

          $tsIp = ""
          if (Test-Path "$env:ProgramFiles\Tailscale\tailscale.exe") {
            try { $tsIp = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4; $tsIp = $tsIp.Trim() } catch {}
          }

          Write-Host "=== INFORMATII ACCES RDP ==="
          if ($mscUser) {
            if ($mscPass) {
              Write-Host "User local: $mscUser  / Parola: $mscPass"
            } else {
              Write-Host "User local: $mscUser  / Parola: (necunoscuta sau neschimbata)"
            }
          } else {
            Write-Host "User local (MSC) : NU a fost gasit in mediu."
          }

          if ($runnerUser) {
            Write-Host "User runneradmin: $runnerUser  / Parola: $runnerPass"
          } else {
            Write-Host "User runneradmin: NU a fost exportat (s-ar fi putut produce eroare anterior)."
          }

          if ($tsIp) { Write-Host "IP Tailscale: $tsIp" } else { Write-Host "IP Tailscale: (nevalabil)" }
          Write-Host "GPU Real Attempt Intel UHD Graphics - risc ban asumat"
          Write-Host "============================"

      - name: Maintaining Connection (ping every 10 min) - fixed loop
        shell: pwsh
        run: |
          for ($i = 0; $i -lt 432; $i++) {
            Write-Host ("Maintaining Connection... Iteration {0} / 432 - {1}" -f $i, (Get-Date))
            Start-Sleep -Seconds 600
          }
          
